### ISSUE TITLE
License

### ISSUE THREAD

**Issue by sbarral** [nnarain/canopen-rs#1]
Hi, we thought about making our own minimalistic CANopen crate, but this looks like it may fit the bill so we would be happy to use it and possibly contribute if our needs become more complex.
I couldn't find the license though, would you consider making it available under the usual MIT+Apache 2.0 dual license?

**Comment by nnarain** [comment]
Ya sure thing. This isn't something I'd say it complete by any means but it is something I'd like to get back to at some point

**Comment by nnarain** [comment]
Added MIT license

**Comment by sbarral** [comment]
Fantastic, thank you very much!
